spring.application.name=Courcedb
spring.datasource.url=jdbc:mysql://localhost:3306/Courcedb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
server.port=2181